version: '3.7'

services:
  postgresql:
    #image: scripts.io/bitnami/scripts:latest
    image: bitnami/postgresql:14.8.0
    container_name: postgresql
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/bitnami/postgresql
      - ./postgresql/scripts:/postgresql-entrypoint-initdb.d
    environment:
      - POSTGRESQL_USERNAME=flight_user
      - POSTGRESQL_PASSWORD=Password1!
      - POSTGRESQL_DATABASE=flight_db
      - POSTGRESQL_HOST=postgresql

  api:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    volumes:
      - ./flightapi:/code/flightapi
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    restart:
      always

#  nginx:
#    image: nginx:1.23.2
#    container_name: nginx
#    restart: always
#    volumes:
#      - ./nginx:/tmp/nginx
#    environment:
#      API_DEV_SERVER_PORT: 8000
#    extra_hosts:
#      - 'host.postgresql.internal:host-gateway'
#    ports:
#      - 80:80
#    depends_on:
#      - api
#    command: bash -c "env && envsubst '$$API_DEV_SERVER_PORT' < /tmp/nginx/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  postgresql_data:
